paths:
  # [DELETE] /api/product
  /api/product:
    delete:
      tags:
        - products
      summary: Delete product
      parameters:
        - name: accessToken
          in: cookie
          description: For user authentication
          required: true
        - name: body
          in: body
          description: product Data
          required: true
          schema:
            type: object
            properties:
              productId:
                type: string
      responses:
        200:
          description: 'Product deleted successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# Product API specification
tags:
  - name: products
    description: products API
